name: smartcard
description: 智慧會員卡錢包 - 完全離線、自動偵測店家、桌面小工具顯示條碼
publish_to: 'none'
version: 1.0.13+15

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  home_widget: ^0.7.0
  barcode_widget: ^2.0.4
  mobile_scanner: ^6.0.0
  geolocator: ^13.0.2
  network_info_plus: ^6.1.0
  permission_handler: ^11.3.1
  package_info_plus: ^8.0.0
  uuid: ^4.5.1
  path_provider: ^2.1.5
  flutter_secure_storage: ^9.2.2
  image_picker: ^1.1.2
  wakelock_plus: ^1.2.10
  shimmer: ^3.0.0
  pointycastle: ^3.9.1
  file_picker: ^8.1.6
  share_plus: ^10.1.4
  http: ^1.2.2
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  firebase_core: ^3.12.1
  firebase_analytics: ^11.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/data/store_locations.json
